# @Author: Arohi Gupta <agupta>
# @Date:   2018-07-06T15:38:49-07:00
# @Email:  agupta@juniper.net
# @Filename: main.yaml
# @Last modified by:   agupta
# @Last modified time: 2018-08-11T15:49:50-07:00

---
- name: Create a new Projects
  ignore_errors: no
  os_project:
    state: present
    name: "{{ item.name }}"
    domain_id: default
    enabled: True
  with_items: "{{ Projects }}"


- name: Add Roles to the new project
  os_user_role:
    user: admin
    role: "{{ item }}"
    project: HR-prod
  with_items:
    - admin
    - _member_

- name: Add Roles to the new project
  os_user_role:
    user: admin
    role: "{{ item }}"
    project: HR-dev
  with_items:
    - admin
    - _member_



- name: Add Users to the new project HR-prod
  ignore_errors: yes
  os_user_role:
    user: "{{ item }}"
    role: _member_
    project: HR-prod
  with_items:
    - heat
    - neutron
    - placement
    - ironic
    - swift
    - barbican
    - glance
    - ironic-inspector
    - nova

- name: Add Users to the new project HR-prod
  ignore_errors: yes
  os_user_role:
    user: "{{ item }}"
    role: _member_
    project: HR-dev
  with_items:
    - heat
    - neutron
    - placement
    - ironic
    - swift
    - barbican
    - glance
    - ironic-inspector
    - nova
- name: Create security group in projects
# Create a security group
  os_security_group:
    auth:
        project_name: "{{item.name}}"
    state: present
    name: test_sg_"{{item.name}}"
    description: security group to test working
  with_items: "{{ Projects }}"
- name: Add rules security group..(TCP rule covering all ports)
# Create a TCP rule covering all ports
  os_security_group_rule:
    auth:
        project_name: "{{item.name}}"
    security_group: test_sg_"{{item.name}}"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  with_items: "{{ Projects }}"
- name: Add rules security group..(UDP rule covering all ports)
# Create a TCP rule covering all ports
  os_security_group_rule:
    auth:
        project_name: "{{item.name}}"
    security_group: test_sg_"{{item.name}}"
    protocol: udp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  with_items: "{{ Projects }}"
- name: Add rules security group..(Allow ICMP)
  os_security_group_rule:
    auth:
        project_name: "{{item.name}}"
    security_group: test_sg_"{{item.name}}"
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0
  with_items: "{{ Projects }}"

- name: Create a test network.
  os_network:
    auth:
        project_name: HR-prod
    state: present
    name: test
    external: true

- name: Create a test network.
  os_network:
    auth:
        project_name: HR-dev
    state: present
    name: test1
    external: true
