# @Author: Arohi Gupta <agupta>
# @Date:   2018-07-06T15:57:19-07:00
# @Email:  agupta@juniper.net
# @Last modified by:   agupta
# @Last modified time: 2018-08-11T15:12:05-07:00

---
#TODO: Uncomment after adding url
- name: Download image #
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
  with_items: "{{ Image }}"

- name: Upload images to openstack
  os_image:
    name: "{{item.name}}"
    container_format: bare
    disk_format: "{{item.disk_format}}"
    state: present
    filename: "{{item.dest}}"
  with_items: "{{ Image }}"

- name: "Create Flavors"
  os_nova_flavor:
    state: present
    name: "{{item.name}}"
    ram: "{{item.ram}}"
    vcpus: "{{item.vcpus}}"
    disk: "{{item.disk}}"
    ephemeral: "{{item.ephemeral}}"
  with_items: "{{ Flavors }}"

- name: Create server instances
  ignore_errors: no
  os_server:
    state: present
    auth:
        project_name: "{{ item.project_name }}"
    name: "{{ item.name }}"
    image: "{{item.image}}"
    flavor: "{{item.flavor}}"
    security_groups: "{{item.sg}}"
    nics:
      - net-name: "{{ item.net_name }}"
      - project-name: "{{ item.project_name }}"
    wait: True
  register: result_ips
  with_items: "{{ VM_Data }}"
  tags: new

- name: "Wait.. to sync vms"
  pause:
    minutes: 5

- import_tasks: internal_ips.yaml
