---
- name: Create a new Projects
  ignore_errors: no
  os_project:
    state: present
    name: "{{ item.name }}"
    domain_id: default
    enabled: True
  with_items: "{{ Projects }}"

- name: Add Roles to the new project
  os_user_role:
    user: admin
    role: "{{ item }}"
    project: HR-dev
  with_items:
    - admin
    - _member_

- name: Add Roles to the new project
  os_user_role:
    user: admin
    role: "{{ item }}"
    project: HR-prod
  with_items:
    - admin
    - _member_

- name: Add Users to the new project HR-dev
  os_user_role:
    user: "{{ item }}"
    role: _member_
    project: HR-dev
  with_items:
    - heat
    - neutron
    - placement
    - ironic
    - swift
    - barbican
    - glance
    - ironic-inspector
    - nova

- name: Add Users to the new project HR-prod
  os_user_role:
    user: "{{ item }}"
    role: _member_
    project: HR-prod
  with_items:
    - heat
    - neutron
    - placement
    - ironic
    - swift
    - barbican
    - glance
    - ironic-inspector
    - nova
