
hosts:
  - ip: 10.10.16.135

# Image: This is used to create image and upload it to openstack
#   - url: http://10.10.4.253/x-traffic1.qcow2
#     name: ubuntu #name of the image
#     dest: /tmp/x-traffic1.qcow2 #directory to store on local machine
#     disk_format: qcow2 #disk_format of the image
Flavors:
  - name: m1.small
    ram: 8192
    vcpus: 4
    disk: 50
    ephemeral: 0
  - name: m1.tiny
    ram: 1024
    vcpus: 1
    disk: 10
    ephemeral: 0
Image:
  - url: http://10.10.4.253/ubuntuimage.qcow2
    name: ubuntu
    dest: /tmp/ubuntuimage.qcow2
    disk_format: qcow2

  - url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    name: cirros
    dest: /tmp/cirros
    disk_format: qcow2

# VM_Data: #This corresponds to the vm parameters
#   - name: web_dev
#     project_name: HR-dev #This corresponds to the Projects created /roles/create_openstack_projects/default/main.yaml
#     net_name: webvndev #This corresponds to the Virtual Networks created in /roles/allow_internet_access/default/main.yaml
#     group: web #This belongs to the tier it belongs to
#     docker: docker run -itd --name web --net=host -e REDMINE_SVC=3.3.3.3 -e REDMINE_SVC_PORT=3000 savvythru/three-tier-proxy
# the docker container it should come up with
VM_Data:
  - name: web_prod
    project_name: HR-prod
    net_name: webvnprod
    group: web
    image: ubuntu
    flavor: m1.small
    sg: test_sg_HR-prod
    order: 3
    docker: docker run -itd --name web --net=host -e REDMINE_SVC=6.6.6.3 -e REDMINE_SVC_PORT=3000 savvythru/three-tier-proxy
    repo: savvythru/three-tier-proxy

  - name: app_dev
    project_name: HR-dev
    net_name: appvndev
    flavor: m1.tiny
    group: app
    sg: test_sg_HR-dev
    image: cirros

  - name: app_prod
    project_name: HR-prod
    net_name: appvnprod
    group: app
    image: ubuntu
    flavor: m1.small
    sg: test_sg_HR-prod
    order: 2
    docker: docker run -itd --name app --net=host -e REDMINE_DB_MYSQL=7.7.7.3 -e REDMINE_DB_PASSWORD=secret savvythru/three-tier-frontend
    repo: savvythru/three-tier-frontend
  - name: db_prod
    project_name: HR-prod
    net_name: dbvnprod
    group: db
    image: ubuntu
    sg: test_sg_HR-prod
    flavor: m1.small
    order: 1
    docker: docker run -itd --name database --net=host -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=redmine savvythru/three-tier-database
    repo: savvythru/three-tier-database
