# @Author: Arohi Gupta <agupta>
# @Date:   2018-07-06T16:12:54-07:00
# @Email:  agupta@juniper.net
# @Last modified by:   agupta
# @Last modified time: 2018-07-25T11:39:09-07:00

# This file contains the default values for this role.
# hosts: #This is for the compute nodes.
#   - name: contrail-node2.contrail-node #enter the hostname of compute node here.
#     ip: 10.87.5.7 #the ip address of the compute node.

hosts:
  - name: contrail-node2.contrail-node
    ip: 10.87.5.7
  - name: contrail-node3
    ip: 10.87.5.6

# Region: #this is used to create aggregate and add hosts to a particular region. ##nova aggregate-list
#   - name: Prod  # name of aggregate
#     availability_zone: France
#     hosts: contrail-node2.contrail-node #host to add.
Region:
  - name: Prod
    availability_zone: France
    hosts: contrail-node2.contrail-node
  - name: Dev
    availability_zone: USA
    hosts:  contrail-node3

# Image: This is used to create image and upload it to openstack
#   - url: http://10.87.129.3/pxe/Standard/dpdkvm/vin/x-traffic1.qcow2
#     name: ubuntu #name of the image
#     dest: /tmp/x-traffic1.qcow2 #directory to store on local machine
#     disk_format: qcow2 #disk_format of the image
Image:
  - url: http://10.87.129.3/pxe/Standard/dpdkvm/vin/x-traffic1.qcow2
    name: ubuntu
    dest: /tmp/x-traffic1.qcow2
    disk_format: qcow2

# VM_Data: #This corresponds to the vm parameters
#   - name: web_dev
#     project_name: HR-dev #This corresponds to the Projects created /roles/create_openstack_projects/default/main.yaml
#     net_name: webvndev #This corresponds to the Virtual Networks created in /roles/allow_internet_access/default/main.yaml
#     group: web #This belongs to the tier it belongs to
#     a_zone: USA #availability_zone
#     docker: docker run -itd --name web --net=host -e REDMINE_SVC=3.3.3.3 -e REDMINE_SVC_PORT=3000 savvythru/three-tier-proxy
# the docker container it should come up with
VM_Data:
  - name: web_dev
    project_name: HR-dev
    net_name: webvndev
    group: web
    a_zone: USA
    image: ubuntu
    docker: docker run -itd --name web --net=host -e REDMINE_SVC=3.3.3.3 -e REDMINE_SVC_PORT=3000 savvythru/three-tier-proxy
  - name: app_dev
    project_name: HR-dev
    net_name: appvndev
    group: app
    a_zone: USA
    image: ubuntu
    docker: docker run -itd --name app --net=host -e REDMINE_DB_MYSQL=4.4.4.3 -e REDMINE_DB_PASSWORD=secret savvythru/three-tier-frontend

  - name: db_dev
    project_name: HR-dev
    net_name: dbvndev
    group: db
    a_zone: USA
    image: ubuntu
    docker: docker run -itd --name database --net=host -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=redmine savvythru/three-tier-database

  - name: web_prod
    project_name: HR-prod
    net_name: webvnprod
    group: web
    a_zone: France
    image: ubuntu
    docker: docker run -itd --name web --net=host -e REDMINE_SVC=6.6.6.3 -e REDMINE_SVC_PORT=3000 savvythru/three-tier-proxy

  - name: app_prod
    project_name: HR-prod
    net_name: appvnprod
    group: app
    a_zone: France
    image: ubuntu
    docker: docker run -itd --name app --net=host -e REDMINE_DB_MYSQL=7.7.7.3 -e REDMINE_DB_PASSWORD=secret savvythru/three-tier-frontend

  - name: db_prod
    project_name: HR-prod
    net_name: dbvnprod
    group: db
    a_zone: France
    image: ubuntu
    docker: docker run -itd --name database --net=host -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=redmine savvythru/three-tier-database
