# @Author: Arohi Gupta <agupta>
# @Date:   2018-08-10T13:44:11-07:00
# @Email:  agupta@juniper.net
# @Filename: playbook.yaml
# @Last modified by:   agupta
# @Last modified time: 2018-08-10T13:53:33-07:00
- hosts: localhost
  become: true
  gather_facts: no
  tasks:
  - name: create docker repo
    yum_repository:
      name: dockerrepo
      description: Docker Repository
      baseurl: https://yum.dockerproject.org/repo/main/centos/7
      gpgkey: https://yum.dockerproject.org/gpg
      gpgcheck: yes

  - name: install docker selinux
    yum:
      name: docker-engine-selinux-17.03.1.ce

  - name: install docker
    yum:
      name: docker-engine-17.03.1.ce
