# @Author: Arohi Gupta <agupta>
# @Date:   2018-07-06T15:57:19-07:00
# @Email:  agupta@juniper.net
# @Last modified by:   agupta
# @Last modified time: 2018-07-25T15:39:53-07:00

---
- name: Download image
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
  with_items: "{{ Image }}"

- name: add host to group 'nodes'
  add_host:
    name: "{{ item.ip }}"
    groups: nodes
    ansible_ssh_host: "{{ item.ip }}"
    ansible_ssh_user: root
  with_items: "{{ hosts }}"
  tags: hosts

- name: Upload images to openstack
  os_image:
    name: "{{item.name}}"
    container_format: bare
    disk_format: "{{item.disk_format}}"
    state: present
    filename: "{{item.dest}}"
  with_items: "{{ Image }}"

- name: Creating Regions.
  os_nova_host_aggregate:
    state: present
    name: "{{ item.name }}"
    availability_zone: "{{ item.availability_zone }}"
    hosts:
      - "{{item.hosts}}"
  with_items: "{{ Region }}"

# - name: Create new keypair from current user's default SSH key
#   os_keypair:
#     state: present
#     name: ansible_key
#     public_key_file: "{{ '~' | expanduser }}/.ssh/id_rsa.pub"

- name: "Create 'Small' flavor with 8192MB of RAM, 4 virtual CPU, and 50GB of local disk"
  os_nova_flavor:
    state: present
    name: m1.small
    ram: 8192
    vcpus: 4
    disk: 50
    ephemeral: 0

- name: Create server instances
  ignore_errors: no
  os_server:
    state: present
    auth:
        project_name: "{{ item.project_name }}"
    name: "{{ item.name }}"
    image: "{{item.image}}"
    flavor: m1.small
    nics:
      - net-name: "{{ item.net_name }}"
      - project-name: "{{ item.project_name }}"
    availability_zone: "{{item.a_zone}}"
    wait: True
  register: result_ips
  with_items: "{{ VM_Data }}"
  tags: new

- name: "Wait.. to sync vms"
  pause:
    minutes: 5

- import_tasks: internal_ips.yaml
